const games={"crossfire": {"icon": "🎯", "name": "CrossFire", "items": [["10,000 ZP", 210], ["20,000 ZP", 405], ["50,000 ZP", 975]]}, "pubg": {"icon": "🎯", "name": "PUBG Mobile", "items": [["60 UC", 58], ["300 + 25 UC", 248], ["600 + 60 UC", 485], ["1500 + 300 UC", 1198], ["3000 + 850 UC", 2385], ["6000 + 2100 UC", 4760]]}, "freefire": {"icon": "🔥", "name": "Free Fire", "items": [["100 Diamonds", 60], ["210 Diamonds", 110], ["530 Diamonds", 260], ["1080 Diamonds", 510], ["2200 Diamonds", 1010]]}, "valorant": {"icon": "🔻", "name": "Valorant", "items": [["شحن Valorant", 258]]}, "steam": {"icon": "🎮", "name": "Steam Wallet", "items": [["بطاقة Steam", 319]]}, "ml": {"icon": "💎", "name": "Mobile Legends", "items": [["10 + 1 Diamonds", 21], ["14 Diamonds", 27], ["42 Diamonds", 53], ["78 + 8 Diamonds", 77], ["156 + 16 Diamonds", 143], ["303 + 33 Diamonds", 264], ["504 + 66 Diamonds", 432]]}, "lol": {"icon": "⚔️", "name": "League of Legends", "items": [["شحن Riot Points", 260]]}, "coc": {"icon": "🛡️", "name": "Clash of Clans", "items": [["شحن اللعبة", 210]]}};
let cart=JSON.parse(localStorage.getItem('bugCart')||'[]');
function save(){localStorage.setItem('bugCart',JSON.stringify(cart));document.getElementById('count').textContent=cart.length}
function addToCart(name,price){cart.push({name:name,price:Number(price)});save();openCart()}
function showGame(id){const g=games[id];document.getElementById('gameTitle').textContent=g.name;document.getElementById('gameDesc').textContent='شحن '+g.name+' بأفضل الأسعار وأمان تام';document.getElementById('prices').innerHTML=g.items.map(x=>'<article class="price"><h3>'+x[0]+'</h3><em>عرض خاص</em><div class="coins">🪙</div><div class="price-row"><b>'+x[1]+' EGP</b><button onclick="addToCart('+JSON.stringify(g.name+' - ')+' + '+JSON.stringify(x[0])+','+x[1]+')">اطلب الآن 🛒</button></div></article>').join('');document.getElementById('recharge').scrollIntoView({behavior:'smooth'})}
function openCart(){document.getElementById('modal').classList.add('show');render()}
function closeCart(){document.getElementById('modal').classList.remove('show')}
function render(){let t=0;document.getElementById('items').innerHTML=cart.length?cart.map((x,i)=>{t+=x.price;return '<div class="row"><span>'+x.name+'</span><span>'+x.price+' جنيه <button onclick="cart.splice('+i+',1);save();render()">حذف</button></span></div>'}).join(''):'<p>السلة فارغة.</p>';document.getElementById('total').textContent=t}
function checkout(){if(!cart.length)return;let t=0,m='مرحباً BUG STORE، أريد طلب:\\n';cart.forEach(x=>{t+=x.price;m+='- '+x.name+': '+x.price+' جنيه\\n'});m+='\\nالإجمالي: '+t+' جنيه';window.open('https://wa.me/201101403738?text='+encodeURIComponent(m),'_blank')}
save();showGame('crossfire');